[package]
name = "rust-pac-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
env_logger = "0.11.5"
log = { version = "0.4.22", features = ["serde"]} 
serde = "1.0.215"
serde_yaml = "0.9.34"
